Ruben
JohnRuben717/aqua-extension-PB pull request #10
Opened 2024-06-24 14:48 UTC by JohnRuben717

2024-06-25 11:03 UTC, rolfheij-sil requested changes
Hey Ruben, I reviewed your changes. Nice work, I'm glad we're making progress! :)
Can you check the comments I left, and update the code accordingly?
Let me know if you have any questions

2024-06-25 11:03 UTC, rolfheij-sil commented on src/main.ts
> +        await decodeAndSchedule(user, pwd);
Please don't use abbreviations like `pwd`. Rename the variable to `password`

2024-06-25 11:03 UTC, rolfheij-sil commented on src/main.ts
>          await papi.storage.writeUserData(token, tokenKey, authToken); // Store the token
Are we actually using this code? Because here we are storing things in `papi.storage`, but in `login.component.tsx` we're storing similar things in `localStorage`. We should pick one or the other.

2024-06-26 07:26 UTC, JohnRuben717 commented on src/main.ts
> +        await decodeAndSchedule(user, pwd);
password keyword is already being used in the line 45
so i think keeping pwd keyword will be fine

2024-06-26 07:26 UTC, JohnRuben717 commented on src/main.ts
>          await papi.storage.writeUserData(token, tokenKey, authToken); // Store the token
i am not sure why i didn't make this part of the code it was Joshua so i will ask him and try to fix it

2024-06-26 07:28 UTC, JohnRuben717 commented on src/data/fetchAssessment.ts
> +  const url = 'https://tmv9bz5v4q.us-east-1.awsapprunner.com/latest/result?assessment_id=1534';
we were told to use `latest`  so we are using it

2024-06-26 07:40 UTC, rolfheij-sil commented on src/components/login.component.tsx
> +    <div>
This is not resolved yet

2024-06-26 07:46 UTC, rolfheij-sil commented on src/main.ts
> +        await decodeAndSchedule(user, pwd);
Nope, check our [coding standard](https://github.com/paranext/paranext/wiki/Code-Style-Guide): `Avoid abbreviations or contractions as part of identifier names`. So in this case, where there's a naming conflict, you will have to think about better/clearer variable names. So for example, the `username` and `password` that you're getting on lines 45 and 46 are coming from storage, so they might be called `storedUsername` and `storedPassword`.

It's important that we use clear and descriptive identifier names

2024-06-26 07:47 UTC, rolfheij-sil commented on src/main.ts
>  const passwordKey = 'storedPassword';
This is not resolved

2024-06-26 09:31 UTC, JohnRuben717 commented on src/main.ts
> +        await decodeAndSchedule(user, pwd);
i fixed the issue

2024-06-26 09:32 UTC, JohnRuben717 commented on src/main.ts
>  const passwordKey = 'storedPassword';
i moved it inside the `activate `function

2024-06-26 09:44 UTC, rolfheij-sil requested changes
Nice, almost there! I've marked a few small things to fix

2024-06-26 09:44 UTC, rolfheij-sil commented on src/types/aqua-extension.d.ts
> +    versionData?: unknown; // Add the assessmentData property
This comment is probably copied over from the line above. And it's not very meaningful/helpful like this ;)

2024-06-26 09:44 UTC, rolfheij-sil commented on src/data/fetch-Bible.ts
Filename should be lower kebab-case, so `fetch-bible.ts`

2024-06-26 09:44 UTC, rolfheij-sil commented on src/data/fetch-Bible.ts
Also, you're not fetching Bibles, right? You're getting a list of version ids that the current user has access to. So maybe think of a better name for this file and function?

2024-06-26 09:51 UTC, JohnRuben717 commented on src/types/aqua-extension.d.ts
> +    versionData?: unknown; // Add the assessmentData property
i fixed it

2024-06-26 09:51 UTC, JohnRuben717 commented on src/data/fetch-Bible.ts
i resolved this issue

2024-06-26 09:57 UTC, rolfheij-sil requested changes
Almost there!

2024-06-26 09:57 UTC, rolfheij-sil commented on src/data/fetch-version.ts
> +async function fetchversion(token: string) {
function names are camelCase ;) So this should be fetchVersion.

Take a look at the `Clear variable names` section of the [Code Style Guide](https://github.com/paranext/paranext/wiki/Code-Style-Guide)

2024-06-26 09:57 UTC, rolfheij-sil commented on src/components/login.component.tsx
> +      // if (response.token) localStorage.setItem(tokenKey, response.token); // Store the token
Why are these commented now? If you don't need them anymore, it's better to just delete them

2024-06-26 12:24 UTC, JohnRuben717 commented on src/components/login.component.tsx
> +      // if (response.token) localStorage.setItem(tokenKey, response.token); // Store the token
I have removed it

2024-06-26 12:26 UTC, rolfheij-sil approved these changes

2024-06-26 12:27 UTC, rolfheij-sil commented
I'm merging the code to main, but we still have to figure out if we're using `localStorage` or `papi.storage`

2024-06-26 12:28 UTC, merged